name: Bulid my Angular app

on:
   push:
    branches: [ main ]

jobs:
   bulid-angular-app:
     runs-on: ubantu-latest

       steps:
      - uses: actions/checkout@v6.0.1
      - name: setup Node js
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: 22.x
      - name: install dependencies
        run: npm install
      - name: Bulid Angular app
        run: npm run Bulid
